/**
 * Local-first image resolver.
 *
 * Reads /images/manifest.json (generated by scripts/bundle-content.mjs)
 * and swaps remote Supabase URLs for locally bundled /images/<file> paths.
 * Falls back to the original remote URL when the local file is missing.
 */

type ManifestMap = Record<string, string>;
type ManifestPayload = ManifestMap | { images?: ManifestMap };

let manifestCache: ManifestMap | null = null;
let manifestPromise: Promise<ManifestMap> | null = null;

function normalize(raw: ManifestPayload | null | undefined): ManifestMap {
  if (!raw) return {};
  if (typeof raw === 'object' && 'images' in raw && raw.images && typeof raw.images === 'object') {
    return raw.images as ManifestMap;
  }
  return raw as ManifestMap;
}

export async function loadImageManifest(): Promise<ManifestMap> {
  if (manifestCache) return manifestCache;
  if (manifestPromise) return manifestPromise;
  manifestPromise = fetch('/images/manifest.json', { cache: 'no-cache' })
    .then((r) => (r.ok ? r.json() : {}))
    .catch(() => ({}))
    .then((m: ManifestPayload) => {
      manifestCache = normalize(m);
      return manifestCache;
    });
  return manifestPromise;
}

if (typeof window !== 'undefined') {
  void loadImageManifest();
}

function lookup(url: string): string | null {
  if (!manifestCache || !url) return null;
  if (manifestCache[url]) return manifestCache[url];
  const bare = url.split('?')[0];
  if (manifestCache[bare]) return manifestCache[bare];
  // Defensive: if caller passed the Supabase render-image variant, try the
  // canonical /object/public/ form that the manifest is keyed by.
  if (bare.includes('/storage/v1/render/image/public/')) {
    const canonical = bare.replace('/storage/v1/render/image/public/', '/storage/v1/object/public/');
    if (manifestCache[canonical]) return manifestCache[canonical];
  }
  return null;
}

/**
 * Synchronous image resolver — safe for `<img src>`.
 * Returns local /images/<file> if known, otherwise the original URL.
 */
export function resolveBundledImage(url: string | null | undefined): string {
  if (!url) return '';
  if (url.startsWith('/images/') || url.startsWith('/placeholder')) return url;
  const local = lookup(url);
  return local || url;
}